all:
    children:
        bastion:
        private_hosts:
    vars:
        ansible_user: ubuntu
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_python_interpreter: /usr/bin/python3
        project: group03

bastion:
    hosts:
        bastion_host:
            ansible_host: 10.0.100.10
    vars:
        subnet: public-subnet

private_hosts:
    hosts:
        storage_servers:
            ansible_host: 10.0.30.10
        security_servers:
            ansible_host: 10.0.30.11
    vars:
        subnet: private-subnet