all:
    children:
        bastion:
        private_hosts:
    vars:
        ansible_user: ubuntu
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ForwardAgent=yes'
        ansible_python_interpreter: /usr/bin/python3
        bastion_host: "{{ hostvars['bastion_host'].ansible_host }}"
        bastion_user: ubuntu
        key_path: /home/minhthien-luu/.credentials/th1enlm02-key.pem
        project: thesis

bastion:
    hosts:
        bastion_host:
            ansible_host: 10.0.100.10
            # ansible_ssh_private_key_file: "{{ key_path }}"
    vars:
        subnet: public-subnet

private_hosts:
    hosts:
        database_servers:
            ansible_host: 10.0.1.10
        storage_servers:
            ansible_host: 10.0.2.10
        mlflow_server:
            ansible_host: 10.0.3.10
    vars:
        subnet: private-subnet
        # ansible_ssh_common_args: >-
        #     -o ProxyCommand="ssh -i /home/minhthien-luu/.credentials/th1enlm02-key.pem -W %h:%p ubuntu@54.209.84.210"
        ansible_ssh_private_key_file: /home/minhthien-luu/.credentials/th1enlm02-key.pem