all:
    children:
        bastion:
        private_hosts:
    vars:
        ansible_user: ubuntu
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ForwardAgent=yes'
        ansible_python_interpreter: /usr/bin/python3
        bastion_host: "{{ hostvars['bastion_host'].ansible_host }}"
        bastion_user: ubuntu
        key_path: ~/.ssh/id_rsa
        project: group03

bastion:
    hosts:
        bastion_host:
            ansible_host: 54.209.84.210
            ansible_ssh_private_key_file: "{{ key_path }}"
    vars:
        subnet: public-subnet

private_hosts:
    hosts:
        storage_servers:
            ansible_host: 10.0.5.10
        registry_servers:
            ansible_host: 10.0.5.11
        infer_servers:
            ansible_host: 10.0.5.12
    vars:
        subnet: private-subnet
        ansible_ssh_common_args: >-
            -o ProxyCommand="ssh -i ~/.ssh/id_rsa -W %h:%p ubuntu@54.209.84.210"
        ansible_ssh_private_key_file: ~/.ssh/kltn