---
- name: Create Harbor directory
  file:
    path: "{{ harbor_home }}"
    state: directory

- name: Download Harbor offline installer
  get_url:
    url: "{{ harbor_installer_url }}"
    dest: "{{ harbor_home }}/harbor-offline-installer.tgz"

- name: Extract Harbor installer
  unarchive:
    src: "{{ harbor_home }}/harbor-offline-installer.tgz"
    dest: "{{ harbor_home }}"
    remote_src: yes

- name: Configure Harbor
  template:
    src: harbor.yml.j2
    dest: "{{ harbor_home }}/harbor/harbor.yml"

- name: Setup insecure registry
  template:
    src: daemon.json.j2
    dest: "{{ docker_insecure_registry }}/daemon.json"
    owner: root
    group: root
    mode: '0775'

- name: Restart Docker Engine
  systemd:
    name: docker
    state: restarted

- name: Prepare Harbor
  command: "{{ harbor_home }}/harbor/prepare"

- name: Install Harbor
  command: "{{ harbor_home }}/harbor/install.sh"
